baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ananke'

[caches]
  [caches.images]
git add .
git commit -m "Remove broken GitHub Actions workflow"
git push
    dir = ':cacheDir/images'
baseURL = "https://aishwarya0-max.github.io/Information-Science-/"
languageCode = "en-us"
title = "Information Science"

